ALTER TABLE `RateOverride` DROP FOREIGN KEY `RateOverride_ratePlanId_fkey`;
ALTER TABLE `RatePlan` DROP FOREIGN KEY `RatePlan_cancellationPolicyId_fkey`;
ALTER TABLE `RatePlan` DROP FOREIGN KEY `RatePlan_derivedFromId_fkey`;
ALTER TABLE `RatePlan` DROP FOREIGN KEY `RatePlan_roomTypeId_fkey`;
DROP TABLE IF EXISTS `LosRule`;
DROP TABLE IF EXISTS `OccupancyRule`;
DROP TABLE IF EXISTS `TaxFeeRule`;
DROP TABLE IF EXISTS `Promotion`;
DROP TABLE IF EXISTS `RateOverride`;
DROP TABLE IF EXISTS `RatePlan`;
DROP TABLE IF EXISTS `CancellationPolicy`;
ALTER TABLE `HotelBooking` DROP COLUMN `pricingSnapshot`;
