-- AlterTable
ALTER TABLE `Site` ADD COLUMN `dining` JSON NULL,
    ADD COLUMN `sourceUrl` VARCHAR(191) NULL,
    MODIFY `category` ENUM('OBIDA', 'MADRASA', 'MASJID', 'MAQBARA', 'MUZEY', 'ARXEOLOGIYA', 'TABIAT', 'BOZOR', 'ZIYORATGOH', 'BOSHQA', 'RESTORAN', 'CHAYXONA', 'KAFE') NOT NULL;

